### ISSUE TITLE
Create a tag/release

### ISSUE THREAD

**Issue by ptr1337** [NVIDIA/egl-x11#8]
Hi together,

im the nvidia co maintainer at archlinux, and we would like to package the egl-x11 library, which will then a dependency for the nvidia-utils package.

It would be helpful to get a tag or release, so that we can package it properly.

**Comment by kbrenneman** [comment]
I've added a tag for version 1.0.0, which should correspond to what's included in the 565.77 installer:
https://github.com/NVIDIA/egl-x11/releases/tag/v1.0.0
